"""empty message

Revision ID: 961965ecfce4
Revises: 1d48ad9fa9a1
Create Date: 2022-04-03 20:44:10.367122

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '961965ecfce4'
down_revision = '1d48ad9fa9a1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('post_tags',
    sa.Column('post_id', sa.Integer(), nullable=True),
    sa.Column('tag_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['post_id'], ['post.id'], ),
    sa.ForeignKeyConstraint(['tag_id'], ['tag.id'], )
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('post_tags')
    # ### end Alembic commands ###
